

export const MIN_MASTER_PW_LENGTH  = 5;
export const MIN_MASTER_PW_SCORE   = 50;

export const PW_GENERATOR_DEFAULT_PW_LENGTH         = 8;
export const PW_GENERATOR_DEFAULT_PW_SCORE          = 60;

export const CHARS_UP       = "ABCDEFGHIJKLMNOPQRSTUVWXYZ";
export const CHARS_LC       = "abcdefghijklmnopqrstuvwxyz";
export const CHARS_NR       = "0123456789";
export const CHARS_SPECIAL  = "()[]{}?!$%&/*+~-,.;:<=>_|@#";

export const VIEW_STATE_EXPORTING_DATA              = 'VIEW_STATE_EXPORTING_DATA';
export const VIEW_STATE_CLEANING_DATA               = 'VIEW_STATE_CLEANING_DATA';
export const VIEW_STATE_LOADING_ALL                 = 'VIEW_STATE_LOADING_ALL';
export const VIEW_STATE_LOADING_ALL_ERROR           = 'VIEW_STATE_LOADING_ALL_ERROR';
export const VIEW_STATE_CREATE_PROFILE              = 'VIEW_STATE_CREATE_PROFILE';
export const VIEW_STATE_LOGIN_REQUIRED              = 'VIEW_STATE_LOGIN_REQUIRED';
export const VIEW_STATE_LOADING_PASSWORDS_ERROR     = 'VIEW_STATE_LOADING_PASSWORDS_ERROR';
export const VIEW_STATE_READY                       = 'VIEW_STATE_READY';
export const VIEW_STATE_LOADING_PASSWORDS           = 'VIEW_STATE_LOADING_PASSWORDS';
export const VIEW_STATE_CONFIRM_REMOVE_PROFILE      = 'VIEW_STATE_CONFIRM_REMOVE_PROFILE';


export const USER_ACTION_OPEN_NEW_PROFILE_VIEW      = 'OPEN_NEW_PROFILE_VIEW';
export const USER_ACTION_SAVE_NEW_PROFILE           = 'SAVE_NEW_PROFILE';

export const USER_ACTION_OPEN_LOGIN_VIEW            = 'OPEN_LOGIN_VIEW';
export const USER_ACTION_DO_LOGIN                   = 'DO_LOGIN';
export const USER_ACTION_DO_LOGOUT                  = 'DO_LOGOUT';
export const USER_ACTION_DO_EXIT                    = 'DO_EXIT';

export const USER_ACTION_OPEN_SETTINGS              = 'OPEN_SETTINGS';
export const USER_ACTION_CANCEL_SETTINGS            = 'CANCEL_SETTINGS';
export const USER_ACTION_SAVE_SETTINGS              = 'SAVE_SETTINGS';
export const USER_ACTION_REMOVE_PROFILE_CONFIRM     = 'REMOVE_PROFILE_CONFIRM';
export const USER_ACTION_REMOVE_PROFILE_CANCEL      = 'REMOVE_PROFILE_CANCEL';
export const USER_ACTION_REMOVE_PROFILE_EXECUTE     = 'REMOVE_PROFILE_EXECUTE';

//
// KATEGORIE
//

export const USER_ACTION_CATEGORY_SELECTED          = 'CATEGORY_SELECTED';
export const USER_ACTION_NEW_CATEGORY               = 'NEW_CATEGORY';
export const USER_ACTION_SAVE_NEW_CATEGORY          = 'SAVE_NEW_CATEGORY';
export const USER_ACTION_EDIT_CATEGORY              = 'EDIT_CATEGORY';
export const USER_ACTION_CANCEL_CATEGORY_SETUP      = 'CANCEL_CATEGORY_SETUP';
export const USER_ACTION_SAVE_EDIT_CATEGORY         = 'SAVE_EDIT_CATEGORY';

export const USER_ACTION_OPEN_CATEGORY_LIST         = 'OPEN_CATEGORY_LIST';
export const USER_ACTION_CLOSE_CATEGORY_LIST        = 'CLOSE_CATEGORY_LIST';

export const USER_ACTION_REMOVE_CATEGORY            = 'REMOVE_CATEGORY';
export const USER_ACTION_EXECUTE_REMOVE_CATEGORY    = 'EXECUTE_REMOVE_CATEGORY';
export const USER_ACTION_CANCEL_REMOVE_CATEGORY     = 'CANCEL_REMOVE_CATEGORY';

//
// PASSWORD
//
export const USER_ACTION_PASSWORD_FILTER            = 'PASSWORD_FILTER';
export const USER_ACTION_NEW_PASSWORD               = 'NEW_PASSWORD';
export const USER_ACTION_SAVE_NEW_PASSWORD          = 'SAVE_NEW_PASSWORD';

export const USER_ACTION_EDIT_PASSWORD              = 'EDIT_PASSWORD';
export const USER_ACTION_SAVE_EDIT_PASSWORD         = 'SAVE_EDIT_PASSWORD';
export const USER_ACTION_CANCEL_PASSWORD_DIALOG      = 'CANCEL_PASSWORD_DIALOG';
export const USER_ACTION_REMOVE_PASSWORD            = 'REMOVE_PASSWORD';
export const USER_ACTION_EXECUTE_REMOVE_PASSWORD    = 'EXECUTE_REMOVE_PASSWORD';
export const USER_ACTION_CANCEL_REMOVE_PASSWORD     = 'CANCEL_REMOVE_PASSWORD';

export const USER_ACTION_MOVE_PASSWORD              = 'MOVE_PASSWORD';
export const USER_ACTION_CANCEL_MOVE_PASSWORD       = 'CANCEL_MOVE_PASSWORD';
export const USER_ACTION_EXECUTE_MOVE_PASSWORD      = 'EXECUTE_MOVE_PASSWORD';

export const USER_ACTION_SHOW_PASSWORD_STRENGTH_DIALOG      = 'SHOW_PASSWORD_STRENGTH_DIALOG';
export const USER_ACTION_CANCEL_PASSWORD_STRENGTH_DIALOG    = 'CANCEL_PASSWORD_STRENGTH_DIALOG';
export const USER_ACTION_COPY_PASSWORD              = 'COPY_PASSWORD';
export const USER_ACTION_COPY_USER_NAME             = 'COPY_USER_NAME';
export const USER_ACTION_SHOW_PASSWORD_GENERATOR_DIALOG      = 'SHOW_PASSWORD_GENERATOR_DIALOG';
export const USER_ACTION_CANCEL_PASSWORD_GENERATOR_DIALOG    = 'CANCEL_PASSWORD_GENERATOR_DIALOG';

export const USER_ACTION_SHOW_TOAST = 'SHOW_TOAST';
//
// IMPORT,EXPORT
//
export const USER_ACTION_EXPORT_PASSWORDS           = 'EXPORT_PASSWORDS';
export const USER_ACTION_IMPORT_PASSWORDS           = 'IMPORT_PASSWORDS';
export const USER_ACTION_EXECUTE_IMPORT_PASSWORDS   = 'EXECUTE_IMPORT_PASSWORDS';
export const USER_ACTION_CANCEL_IMPORT_PASSWORDS    = 'CANCEL_IMPORT_PASSWORDS';

export const DEV_USER_ACTION_RESET_DB               = 'DEV_USER_ACTION_RESET_DB';
export const DEV_USER_ACTION_SHOW_DB                = 'DEV_USER_ACTION_SHOW_DB';
export const DEV_USER_ACTION_HIDE_DB                = 'DEV_USER_ACTION_HIDE_DB';

//
export const USER_ACTION_OPEN_ABOUT                = 'OPEN_ABOUT';
export const USER_ACTION_CLOSE_ABOUT               = 'CLOSE_ABOUT';

export const USER_ACTION_OPEN_ABOUT_ENCRYPTION_INFO  = 'OPEN_ABOUT_ENCRYPTION_INFO';
export const USER_ACTION_CLOSE_ABOUT_ENCRYPTION_INFO = 'CLOSE_ABOUT_ENCRYPTION_INFO';

export const USER_ACTION_OPEN_HOWTO  = 'OPEN_HOWTO';
export const USER_ACTION_CLOSE_HOWTO = 'CLOSE_HOWTO';

export const USER_ACTION_RESET_SESSION_TIMER  = 'USER_ACTION_RESET_SESSION_TIMER';

export const CFG_LOG_APP          = true;
export const CFG_LOG_REPOSITORIES = false;
export const CFG_LOG_DATALOADER   = false;

//
// #D58705
//

export const THEME = {

    'dark': {

        COLOR_ACCENT : '#E89805',
        COLOR_ACCENT_2 : '#317331',

        COLOR_TITLEBAR_BACKGROUND : '#24292e',
        COLOR_TITLEBAR_BORDER : '#191919',

        COLOR_TITLEBAR_MENU_TEXT : '#E89805',
        COLOR_TITLEBAR_MENU_HOVER_BACKGROUND : '#191919',
        COLOR_TITLEBAR_MENU_ITEM_HOVER_BACKGROUND : '#24292e',
        COLOR_TITLEBAR_MENU_ITEM_HOVER_TEXT : '#E89805',

        COLOR_TOOLBAR_BACKGROUND : '#24292e',
        COLOR_TOOLBAR_SECTION_BORDER : '#191919',
        COLOR_TOOLBAR_SELECTOR_TRIANGLE : '#666',

        COLOR_TOOLBAR_SEARCH_INPUT_BACKGROUND : '#4d4d4d',

        COLOR_NAVIGATION_OPENED_BACKGROUND : '#24292e',
        COLOR_NAVIGATION_OPENED_CATEGORY_NAME : '#a9a9a9',
        COLOR_NAVIGATION_OPENED_CATEGORY_VALUE : '#c2c2c2',

        COLOR_NAVIGATION_CLOSED_BACKGROUND      : '#24292e',
        COLOR_NAVIGATION_CLOSED_CATEGORY_NAME   : '#a9a9a9',
        COLOR_NAVIGATION_CLOSED_CATEGORY_VALUE  : '#c2c2c2',

        COLOR_NAVIGATION_LIST_SELECTED_ITEM_BACKGROUND : '#191919',
        COLOR_NAVIGATION_LIST_SELECTED_ITEM_TEXT : '#E89805',
        COLOR_NAVIGATION_LIST_SELECTED_ITEM_BORDER : '#E89805',
        COLOR_NAVIGATION_LIST_ITEM_HOVER_BACKGROUND : '#191919',
        COLOR_NAVIGATION_LIST_CATEGORY_ITEM_NAME : '#a9a9a9',
        COLOR_NAVIGATION_LIST_SEARCH_INPUT_BACKGROUND : '#4d4d4d',

        COLOR_DIALOG_TITLE_BACKGROUND : '#24292e',
        COLOR_DIALOG_TITLE_TEXT : '#E89805',
        COLOR_DIALOG_WARNING_TITLE_BACKGROUND: '#d6140a',
        COLOR_DIALOG_WARNING_TITLE_TEXT: '#fff',

        COLOR_PASSWORD_ITEM_TITLE : '#4d4d4d',

    },

    'dark-mixed': {

        COLOR_ACCENT : '#E89805',
        COLOR_ACCENT_2 : '#2c42e8',

        COLOR_TITLEBAR_BACKGROUND : '#24292e',
        COLOR_TITLEBAR_BORDER : '#191919',

        COLOR_TITLEBAR_MENU_TEXT : '#E89805',
        COLOR_TITLEBAR_MENU_HOVER_BACKGROUND : '#191919',
        COLOR_TITLEBAR_MENU_ITEM_HOVER_BACKGROUND : '#24292e',
        COLOR_TITLEBAR_MENU_ITEM_HOVER_TEXT : '#E89805',

        COLOR_TOOLBAR_BACKGROUND : '#24292e',
        COLOR_TOOLBAR_SECTION_BORDER : '#191919',
        COLOR_TOOLBAR_SELECTOR_TRIANGLE : '#666',

        COLOR_TOOLBAR_SEARCH_INPUT_BACKGROUND : '#4d4d4d',

        COLOR_NAVIGATION_OPENED_BACKGROUND : '#fff',
        COLOR_NAVIGATION_CLOSED_BACKGROUND : '#24292e',

        COLOR_NAVIGATION_CLOSED_CATEGORY_NAME : '#a9a9a9',
        COLOR_NAVIGATION_CLOSED_CATEGORY_VALUE : '#c2c2c2',

        COLOR_NAVIGATION_OPENED_CATEGORY_NAME : '#444444',
        COLOR_NAVIGATION_OPENED_CATEGORY_VALUE : '#444444',

        COLOR_NAVIGATION_LIST_SELECTED_ITEM_BACKGROUND : '#f2f2f2',
        COLOR_NAVIGATION_LIST_SELECTED_ITEM_TEXT : '#E89805',
        COLOR_NAVIGATION_LIST_SELECTED_ITEM_BORDER : '#E89805',
        COLOR_NAVIGATION_LIST_ITEM_HOVER_BACKGROUND : '#4e4e4e',
        COLOR_NAVIGATION_LIST_CATEGORY_ITEM_NAME : '#4e4e4e',
        COLOR_NAVIGATION_LIST_SEARCH_INPUT_BACKGROUND : '#4d4d4d',

        COLOR_DIALOG_TITLE_BACKGROUND : '#24292e',
        COLOR_DIALOG_TITLE_TEXT : '#E89805',
        COLOR_DIALOG_WARNING_TITLE_BACKGROUND: '#a1030b',
        COLOR_DIALOG_WARNING_TITLE_TEXT: '#fff',

        COLOR_PASSWORD_ITEM_TITLE : '#444',
    }
};




